# Generated by Django 3.0.6 on 2021-01-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='standard',
            field=models.IntegerField(blank=True, verbose_name='Class'),
        ),
    ]
