# Generated by Django 3.0.6 on 2021-01-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210127_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Full Name'),
        ),
    ]
