# Generated by Django 3.0.6 on 2021-01-28 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTests',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Test ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Test Date')),
                ('total_marks', models.IntegerField(default=100, verbose_name='Max Marks')),
                ('subject', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Conduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student', verbose_name='Student ID')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Teacher', verbose_name='Teacher ID')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_conducts.StudentTests', verbose_name='Test ID')),
            ],
            options={
                'unique_together': {('test_id', 'student_id')},
            },
        ),
    ]
