# Generated by Django 3.0.6 on 2021-02-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_conducts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttests',
            name='standard',
            field=models.IntegerField(blank=True, verbose_name='Class'),
        ),
    ]
